### ISSUE TITLE
Does Bluebox allow testing against different Linux kernel versions?

### ISSUE THREAD

**Issue by yzhao1012** [florianl/bluebox#40]
Background:
Pixie (https://github.com/pixie-io/pixie) is based on eBPF, eBPF supports vary widely across different versions of Linux Kernel versions (because it's still relatively new feature in Linux Kernel).

Pixie constantly tests our eBPF code across different versions of Linux Kernels.
Currently, that's done by testing on an oldest supported kernel (4.14 now), and another on the newest LTS kernel version.
That is problematic because Pixie wanted to provide fine-grained information about what features are supported on different Linux Kernel versions.

Objective:
We'd like to have bluebox environment for different kernel versions. So that we can test Pixie's eBPF code on the corresponding Linux Kernels.

Is that possible?

**Comment by florianl** [comment]
Hi 
The usecase you describe matches exactly the reason why [bluebox](https://github.com/florianl/bluebox) was created. It enables its users to create something that can be tested against a variety of Linux Kernels. E.g. it is currently used at [Elastic](https://github.com/elastic/ebpf/tree/main/testing#elastic-ebpf-multi-kernel-tester) to test eBPF on multiple Linux Kernels and different architectures.
