### ISSUE TITLE
Setting environment variables?

### ISSUE THREAD

**Issue by DirectorX** [florianl/bluebox#73]

**Comment by florianl** [comment]
Can you please provide a bit more context? Without further context it is hard to answer this question. What do you want to achieve? What did you try to achieve it?

**Comment by florianl** [comment]
With https://github.com/florianl/bluebox/pull/74 an option was introduced to set environment variables. Please check it out and provide feedback.

**Comment by florianl** [comment]
Closing due to missing response. Reported issue should be resolved with https://github.com/florianl/bluebox/pull/74 - please feel free to open a new issue otherwise.
